---
# Install MySQL
- name: Install MySQL / MariaDB
  vars:
    packages_Suse: ['mariadb', 'mariadb-client', 'python-mysql']
    packages_RedHat: ['mariadb-server', 'mariadb', 'MySQL-python']
    packages_Debian: ['mysql-server', 'mysql-client', 'python-mysqldb']
  package: name={{ item }} state=present
  with_items: "{{ vars['packages_' + ansible_os_family] }}"
  register: mysql_result

- name: Ensure mysql is running and starts on boot
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  become: yes
  register: mysql_result

- name: Ensure mysql root password is updated for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "admin123"
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
  loop:
    - "{{ ansible_hostname }}"
    - "{{ ansible_fqdn }}"
    - 127.0.0.1
    - ::1
    - localhost
  become: yes
  register: mysql_result


- name: Start the mysqld service
  vars:
    service_Suse: mysql
    service_RedHat: mariadb
    service_Debian: mysql
  service: name={{ vars['service_' + ansible_os_family] }} state=restarted enabled=yes
  when: mysql_result.changed
